spring.datasource.url=jdbc:postgresql://localhost:5433/antonialucia
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=guilhermevieira
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.main.allow-circular-references=true