INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ACRELANDIA', 'FAZENDA', 'INFRAESTRUTURA URBANA - TE', 190000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ACRELANDIA', 'MAPA', 'SETE DISTRIBUIDORES DE CALCÁRIO - CAPACIDADE DE 5 A 7 TONELADAS', 296350.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ACRELANDIA', 'MS/FNS', 'VEÍCULO PARA TRANSPORTE ELETIVO DE PACIENTE COM ACESSIBILIDADE PARA 1 CADEIRANTE', 316956.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ACRELANDIA', 'MS/FNS', 'CUSTEIO PAP/SAÚDE', 300000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ACRELANDIA', 'MAPA', 'FOMENTO AO SETOR AGROPECUÁRIO', 1000000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ACRELANDIA', 'MIDR', 'CAMINHÃO PIPA 12.000 LITROS', 557679.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ACRELANDIA', 'MIDR', 'MICRO TRATOR AGRÍCOLA 14CV', 22309.51);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ACRELANDIA', 'MIDR', 'PLANTADEIRA E ADUBADEIRA DE GRÃOS 4 LINHAS', 24700.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ACRELANDIA', 'MIDR', 'GRADE NIVELADORA 28X22"', 28880.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ACRELANDIA', 'MIDR', 'GRADE ARADORA 14X26"', 20500.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ACRELANDIA', 'MIDR', 'CAMINHÃO CARGA SECA 7M 4X2 185CV', 411000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ACRELANDIA', 'MIDR', 'DUAS CAMINHONETES 4X4 CABINE DUPLA', 451690.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ACRELANDIA', 'MIDR', 'VEÍCULO HATCH 1.0', 101000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ACRELANDIA', 'MIDR', '17 MOTOCICLETAS BROS 160', 390830.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ASSIS BRASIL', 'ESPORTE', 'INFRAESTRUTURA ESPORTIVA', 220357.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ASSIS BRASIL', 'MS/FNS', 'Impressora Laser / Estante / Mesa de Escritório / Ultrassom Diagnóstico / Computador / Cadeira para Obeso / Balde a Pedal / Ar Condicionado / Consultório Odontológico Portátil / Veículo e Motocicleta para Transporte de Equipe', 316963.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ASSIS BRASIL', 'MS/FNS', 'REFORMA DA UBS Terezinha Batista dos Santos', 400010.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ASSIS BRASIL', 'MS/FNS', 'REFORMA DA UBS Antônio Alves Cavalcante', 399971.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ASSIS BRASIL', 'MS/FNS', 'INCREMENTO PAP', 500000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ASSIS BRASIL', 'MIDR', 'VEÍCULO HATCH 1.0', 101000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ASSIS BRASIL', 'MIDR', 'TRÊS TRATORES AGRÍCOLAS 110 CV', 578997.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ASSIS BRASIL', 'MIDR', 'CAMINHÃO PIPA 6.000 LITROS - 4X2 -175CV', 464417.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ASSIS BRASIL', 'MIDR', 'DOIS TRICICLOS DE CARGA 149CC', 66000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ASSIS BRASIL', 'CULTURA', 'EVENTO: 5ª SEMANA EVANGÉLICA E 5ª MARCHA PARA JESUS', 500000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ASSIS BRASIL', 'CULTURA', 'EVENTO EXPOFRONTEIRA', 1500000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ASSIS BRASIL', 'ESPORTE', 'APOIO A REALIZAÇÃO DE EVENTO DE ESPORTE,LAZER E INCLUSÃO SOCIAL', 286788.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('ASSIS BRASIL', 'MIDR', 'PÁ CARREGADEIRA SOBRE RODAS', 287900.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('BRASILEIA', 'DEFESA', 'CONSTRUÇÃO DA SEDE DA DEFENSORIA PÚBLICA', 1537600.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('BRASILEIA', 'MS/FNS', '3 Motocicletas para Transporte de Equipe / Consultório Odontológico Portátil / Mesa Ginecológica / 9 Geladeiras-Refrigerador / 14 Bebedouros Purificador Refrigerado / 9 Impressoras Laser / 7 Estante / 3 Tablet / 5 Lanternas Clínicas / 3 Laringoscópios Adulto / 6 Armários Vitrine / Mesa de Exames', 186000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('BRASILEIA', 'MS/FNS', 'EQUIPAMENTOS PARA ÁREA DA SAÚDE', 999858.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('BRASILEIA', 'MS/FNS', 'INCREMENTO PAP', 500000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('BRASILEIA', 'MS/FNS', 'INCREMENTO PAP', 560000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('BRASILEIA', 'MS/FNS', 'INCREMENTO MAC', 500000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('BUJARI', 'DEFESA', 'PAVIMENTAÇÃO EM TIJOLOS MACIÇOS EM VIA URBANA COM DRENAGEM E CALÇADAS', 500000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('BUJARI', 'DEFESA', 'PARQUE DA VAQUEJADA', 1441500.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('BUJARI', 'CIDADES', 'PAVIMENTAÇÃO DE VIAS URBANAS', 882383.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('BUJARI', 'MS/FNS', 'INCREMENTO PAP', 500000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('BUJARI', 'MIDR', 'VAN 16 PASSAGEIROS', 300777.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('BUJARI', 'MS/FNS', 'INCREMENTO PAP', 1075302.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('BUJARI', 'MIDR', 'TRATOR AGRÍCOLA 110CV', 192999.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('BUJARI', 'MIDR', 'VEÍCULO HATCH 1.0', 101000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CAPIXABA', 'MS/FNS', 'Ultrassom Diagnóstico / Veículo e Motocicleta Para Transporte de Equipe / Esfigmomanômetro Adulto / Impressora Laser / Duas Lanternas Clínica / 2 Esfigmomanômetros Infantil  / Escada com 2 degraus / Ar Condicionado / Mesa Ginecológica / Mesa de Escritório / Consultório Odontológico / Computador', 316961.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CAPIXABA', 'MS/FNS', 'CUSTEIO PAP/SAÚDE', 360000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CAPIXABA', 'MS/FNS', 'CUSTEIO PAP/SAÚDE', 50988.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CAPIXABA', 'MAPA', 'PÁ CARREGADEIRA SOBRE RODAS', 764800.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CAPIXABA', 'MS/FNS', 'EQUIPAMENTOS PARA ÁREA DA SAÚDE', 269786.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CAPIXABA', 'MS/FNS', 'INCREMENTO PAP', 868000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CAPIXABA', 'MS/FNS', 'INCREMENTO MAC', 400000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CAPIXABA', 'MIDR', 'PÁ CARREGADEIRA 100 CV', 287900.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CAPIXABA', 'MIDR', 'ÔNIBUS EXECUTIVO 40 LUGARES', 907268.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CAPIXABA', 'MS/FNS', 'INCREMENTO PAP', 800000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CAPIXABA', 'CULTURA', 'EVENTO: SEMANA EVANGÉLICA', 300000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CAPIXABA', 'CULTURA', 'EVENTO: EXPOCAPIXABA', 1500000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CAPIXABA', 'MS/FNS', 'EQUIPAMENTOS PARA ÁREA DA SAÚDE', 428570.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CAPIXABA', 'MIDR', 'DOIS TRICICLOS DE CARGA 149CC', 66000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CAPIXABA', 'MIDR', 'VEÍCULO HATCH 1.0', 101000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CRUZEIRO DO SUL', 'DEFESA', 'PROJETO LAGOINHA', 1067740.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CRUZEIRO DO SUL', 'MAPA', 'GRADE NIVELADORA / DUAS GRADES ARADORAS / 1 TRATOR DE PNEUS 4X4 DE 100 CV / 15 ROÇADEIRAS', 569020.9);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CRUZEIRO DO SUL', 'ESPORTE', 'INFRAESTRUTURA ESPORTIVA', 1982726.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CRUZEIRO DO SUL', 'MS/FNS', 'CUSTEIO MAC/SAÚDE', 810000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CRUZEIRO DO SUL', 'MDAS', 'APOIO, MANUTENÇÃO E PROVISÃO AOS  SERVIÇOS DE ASSISTÊNCIA SOCIAL', 990000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CRUZEIRO DO SUL', 'MIDR', 'CAMINHONETE 4X4 CABINE DUPLA', 225845.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CRUZEIRO DO SUL', 'MIDR', '9 TRATORES AGRICOLAS 110CV', 1736991.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CRUZEIRO DO SUL', 'MIDR', 'VEÍCULO HATCH 1.0', 101000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('CRUZEIRO DO SUL', 'TURISMO', 'Apoio a Realização de Evento para a Promoção da Atividade Turística Local e Posicionamento no Mercado Turístico - Festival Gastronômico do Juruá: Amazônia em Sabores – 1ª Edição', 729976.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('EPITACIOLÂNDIA', 'DEFESA', 'PARQUE DA VAQUEJADA', 961500.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('EPITACIOLÂNDIA', 'MS/FNS', 'Ultrassom Diagnóstico / Veículo e Motocicleta Para Transporte de Equipe / Ventilador de Teto / Mesa de Escritório / Martelo de Reflexo / Estante / Ar Condicionado / Impressora Laser / Refletor Odontológico / Consultório Odontológico Portátil / Computador ', 316987.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('EPITACIOLÂNDIA', 'MS/FNS', 'CUSTEIO PAP/SAÚDE', 1500000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('EPITACIOLÂNDIA', 'MS/FNS', 'INCREMENTO PAP', 1500000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('EPITACIOLÂNDIA', 'CIDADES', 'PAVIMENTAÇÃO', 1000000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('EPITACIOLÂNDIA', 'CULTURA', 'EVENTO', 1500000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('EPITACIOLÂNDIA', 'CULTURA', 'CONSTRUÇÃO DO MUSEU DA MÚSICA', 860661.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('EPITACIOLÂNDIA', 'MS/FNS', 'INCREMENTO PAP', 1400000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('EPITACIOLÂNDIA', 'ESPORTE', 'APOIO A REALIZAÇÃO DE EVENTO ESPORTIVO', 595588.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('EPITACIOLÂNDIA', 'MS/FNS', 'INCREMENTO PAP', 940337.6);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('EPITACIOLÂNDIA', 'MIDR', 'CAMINHONETE 4X4 CABINE DUPLA', 225845.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('EPITACIOLÂNDIA', 'MIDR', 'PÁ CARREGADEIRA', 287900.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('EPITACIOLÂNDIA', 'CIDADES', 'PAVIMENTAÇÃO DE VIAS URBANAS', 5600000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('EPITACIOLÂNDIA', 'MIDR', 'CINCO TRATORES AGRÍCOLAS 110CV', 964995.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('EPITACIOLÂNDIA', 'MIDR', 'DOIS TRATORES AGRÍCOLAS 75CV', 276000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('EPITACIOLÂNDIA', 'MIDR', '20 MOTOCICLETAS BROS 160', 459800.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('FEIJÓ', 'DEFESA', 'PARQUE DA VAQUEJADA', 1345000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('FEIJÓ', 'MS/FNS', 'Ultrassom Diagnóstico / Veículo Para Transporte de Equipe / 2 No-Break / Computador / Mesa de Escritório / Computador (Desktop) / Computador Servidor Médio e Grande Porte / Rack de Servidor / Roteador (LAN) / Mesa para Impressora', 313296.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('FEIJÓ', 'MS/FNS', 'CUSTEIO PAP/SAÚDE', 300000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('FEIJÓ', 'DEFESA', '1 ÔNIBUS 30 PASSAGEIROS', 607643.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('FEIJÓ', 'MIDR', 'PAVIMENTAÇÃO DE ESTRADAS VICINAIS', 709646.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('FEIJÓ', 'DEFESA', 'ROLO COMPACTADOR E TRATOR', 913000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('FEIJÓ', 'TURISMO', 'CONSTRUÇÃO DE CENTRO CULTURAL', 1316228.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('FEIJÓ', 'EDUCAÇÃO', 'EQUIPAMENTOS DE: CLIMATIZAÇÃO / DE TECNOLOGIA DA INFORMAÇÃO E COMUNICAÇÃO / DE COZINHA / AQUISIÇÃO DE MOBILIÁRIO', 1971060.2);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('FEIJÓ', 'MS/FNS', 'CUSTEIO PAP/SAÚDE', 240866.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('FEIJÓ', 'MS/FNS', 'EQUIPAMENTOS PARA ÁREA DA SAÚDE', 428570.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('FEIJÓ', 'MIDR', 'DOIS CAMINHÕES PIPA 6.000 LITROS 4X2 - 185CV', 928834.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('FEIJÓ', 'MIDR', 'CAMINHÃO BASCULANTE 6 M³- 4X2 - 185 CV', 430500.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('JORDÃO', 'MS/FNS', 'Ultrassom Diagnóstico / Veículo e Motocicleta Para Transporte de Equipe / Computador / Mesa de Escritório / Balança Digital / Impressora Laser / Biombo / Ar Condicionado / Consultório Odontológico Portátil', 316989.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('JORDÃO', 'MIDR', 'TRATOR DE PNEUS 4 X 4 - 75CV', 238750.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('JORDÃO', 'MAPA', '57 ROÇADEIRAS', 119443.25);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('JORDÃO', 'MIDR', 'ESCAVADEIRA HIDRÁULICA', 792124.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('JORDÃO', 'MS/FNS', 'INCREMENTO PAP', 1000000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('JORDÃO', 'MS/FNS', 'INCREMENTO PAP', 522371.54);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('JORDÃO', 'MS/FNS', 'INCREMENTO PAP', 500000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('JORDÃO', 'MIDR', 'CAMINHÃO PIPA 12.000 LITROS - 6X2 - 200CV', 557679.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('JORDÃO', 'MIDR', 'CAMINHÃO PIPA 6.000 LITROS - 4X2 - 175CV', 464417.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('JORDÃO', 'MIDR', 'ESCAVADEIRA HIDRAULICA 90CV', 474200.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('JORDÃO', 'MIDR', 'MINICARREGADEIRA 58 CV BOBCAT', 211500.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('JORDÃO', 'MIDR', 'TRATOR AGRÍCOLA 75CV', 222200.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MÂNCIO LIMA', 'MAPA', 'CINCO GRADES DE 16 DISCOS E 4 ROÇADEIRAS MANUAIS ', 296450.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MÂNCIO LIMA', 'MS/FNS', 'Ultrassom Diagnóstico / 30 Tablet / 8 Computadores Portáteis (Notebook)', 316900.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MÂNCIO LIMA', 'DEFESA', '1 ÔNIBUS 30 PASSAGEIROS', 672700.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MÂNCIO LIMA', 'DEFESA', 'PARQUE DA VAQUEJADA', 1441450.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MÂNCIO LIMA', 'MS/FNS', 'EQUIPAMENTOS PARA ÁREA DA SAÚDE', 995896.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MÂNCIO LIMA', 'MS/FNS', 'INCREMENTO PAP', 1000000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MÂNCIO LIMA', 'MIDR', 'VEÍCULO HATCH 1.0', 101000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MÂNCIO LIMA', 'MIDR', 'ÔNIBUS EXECUTIVO 40 LUGARES', 907268.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MÂNCIO LIMA', 'MIDR', 'TRÊS QUADRICICLOS 300CC', 135000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MÂNCIO LIMA', 'MIDR', 'MOTONIVELADORA + TRATOR', 955000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MÂNCIO LIMA', 'MS/FNS', 'INCREMENTO PAP', 1181780.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MÂNCIO LIMA', 'MS/FNS', 'EQUIPAMENTOS PARA ÁREA DA SAÚDE', 428570.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MÂNCIO LIMA', 'ESPORTE', 'INFRAESTRUTURA ESPORTIVA', 1085404.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MÂNCIO LIMA', 'TURISMO', 'CONSTRUÇÃO DA PRAÇA DO TAXISTA', 400000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MÂNCIO LIMA', 'MIDR', 'PÁ CARREGADEIRA SOBRE RODAS', 287900.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MANOEL URBANO', 'ESPORTE', 'INFRAESTRUTURA ESPORTIVA', 220300.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MANOEL URBANO', 'MS/FNS', '1 Veículo e 4 Motocicletas Para Transporte de Equipe / 10 No-Break  / 2 Computadores Servidor de Médio e Grande Porte / Impressora Laser / 4 Switch / 2 Rack de Servidor / 2 Computadores Desktop-Avançado / 5 Impressoras Laser Multifuncionais', 316504.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MANOEL URBANO', 'MS/FNS', 'CUSTEIO PAP/SAÚDE', 300000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MANOEL URBANO', 'DEFESA', '1 ÔNIBUS 30 PASSAGEIROS', 672700.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MANOEL URBANO', 'DEFESA', '17 BARCOS COM RABETA', 452166.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MANOEL URBANO', 'MIDR', 'AQUISIÇÃO DE RETROESCAVADEIRA, CARREGADEIRA E IMPLEMENTOS AGRÍCOLAS', 791742.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MANOEL URBANO', 'MS/FNS', 'EQUIPAMENTOS PARA ÁREA DA SAÚDE', 999578.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MANOEL URBANO', 'MS/FNS', 'INCREMENTO PAP', 1000000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MANOEL URBANO', 'MIDR', 'VEÍCULO HATCH 1.0', 101000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MANOEL URBANO', 'MIDR', 'CAMINHÃO CARGA SECA 7M 4X2 185CV', 411000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MANOEL URBANO', 'MIDR', 'RETROESCAVADEIRA 80CV', 335000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MANOEL URBANO', 'MS/FNS', 'INCREMENTO PAP', 1060000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MANOEL URBANO', 'MS/FNS', 'EQUIPAMENTOS PARA ÁREA DA SAÚDE', 428570.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MANOEL URBANO', 'MIDR', 'TRÊS TRATORES AGRÍCOLAS 75CV', 414000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MANOEL URBANO', 'MIDR', 'CAMINHONETE 4X4 CABINE DUPLA', 225845.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MARECHAL THAUMATURGO', 'MS/FNS', 'Mesa Ginecológica / Biombo / Ar Condicionado / Martelo de Reflexo / Impressora Laser / Mesa de Escritório / Ultrassom / Lanternas Clínicas / Computador / Consultório Odontológico Portátil / Veículo e Motocicleta para transporte de Equipe', 316976.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MARECHAL THAUMATURGO', 'MS/FNS', 'CUSTEIO PAP/SAÚDE', 300000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MARECHAL THAUMATURGO', 'MS/FNS', 'INCREMENTO PAP', 1000000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MARECHAL THAUMATURGO', 'MIDR', 'MOTONIVELADORA (R$ 724.500)', 1350000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MARECHAL THAUMATURGO', 'MIDR', 'QUATRO TRICICLOS DE CARGA 149CC', 132000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MARECHAL THAUMATURGO', 'MIDR', 'SETE MICROTRATORES AGRÍCOLAS 14CV', 156166.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MARECHAL THAUMATURGO', 'MS/FNS', 'INCREMENTO PAP', 1060000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('MARECHAL THAUMATURGO', 'MIDR', 'CAMINHONETE PICAPE 4X4 CABINE DUPLA', 225845.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PLÁCIDO DE CASTRO', 'MAPA', 'DUAS GRADES ARADORAS DE 16 DISCOS - UMA GRADE NIVELADORA DE 28 DISCOS - TRÊS DISTRIBUIDORES DE CALCÁRIO COM CAPACIDADE DE 5 A 7,5 TONELADAS - UM PULVERIZADOR MATERIAL TANQUE', 296050.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PLÁCIDO DE CASTRO', 'FAZENDA', 'INFRAESTRURA URBANA - TE', 190000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PLÁCIDO DE CASTRO', 'MS/FNS', 'Veículo Pick-up Cabine Dupla 4x4 (Diesel) / 8 Mesas de Escritório / 4 Ar Condicionados / 7 Armários / 21 Cadeiras / 5 Ar Condicionados / 2 Mesa de Exames / 2 Biombos / Escada com 2 degraus / 2 Esfigmomanômetro Infantil / Estadiômetro 1 / 2 Esfigmomanômetro Adulto / Adipômetro / Estetoscópio Infantil / Balança Antropométrica para Obesos / Mesa Ginecológica / Cadeira para Obeso / Impressora Laser / Computador Desktop Avançado / Televisor / 3 Longarinas / Cadeira de Rodas para Obeso / Bebedouro- Purificador Refrigerado  / 2 Armários Vitrine', 316950.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PLÁCIDO DE CASTRO', 'DEFESA', '1 ÔNIBUS 30 PASSAGEIROS (IVECO)', 607643.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PLÁCIDO DE CASTRO', 'MIDR', 'PAVIMENTAÇÃO DE ESTRADAS VICINAIS', 1172453.64);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PLÁCIDO DE CASTRO', 'MS/FNS', 'CUSTEIO PAP/SAÚDE', 1000000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PLÁCIDO DE CASTRO', 'DEFESA', 'ESCOLA JOAO BATISTA LOPES DE LIMA', 2865000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PLÁCIDO DE CASTRO', 'MS/FNS', 'INCREMENTO PAP', 1900000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PLÁCIDO DE CASTRO', 'MIDR', 'DOIS VEICULOS HATCH 1.0', 202000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PLÁCIDO DE CASTRO', 'MIDR', 'CAMINHÃO BASCULANTE 12M³ 6X4 270CV', 594305.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PLÁCIDO DE CASTRO', 'MIDR', '23 MOTOCICLETAS BROS 160', 528770.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PLÁCIDO DE CASTRO', 'MS/FNS', 'CONSTRUÇÃO UBS NA VILA DA ENCO', 2100000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PLÁCIDO DE CASTRO', 'MS/FNS', 'INCREMENTO PAP', 2000000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PLÁCIDO DE CASTRO', 'MS/FNS', 'INCREMENTO PAP', 2130910.57);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PLÁCIDO DE CASTRO', 'MIDR', '22 CARRETA AGRICOLA BASCULANTE 4T', 413600.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PLÁCIDO DE CASTRO', 'MIDR', 'TRÊS TRATORES AGRICOLAS 75CV', 414000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PLÁCIDO DE CASTRO', 'MIDR', '5 CAMINHÕES CARGA SECA 7M 4X2 185CV', 2055000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO ACRE', 'DEFESA', '11 MOTOCICLETAS E 02 QUADRICICLOS', 480500.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO ACRE', 'DEFESA', 'PAVIMENTAÇÃO DE ESTRADAS VICINAIS', 2390000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO ACRE', 'FNAS/MDASFCF', 'ESTRUTURAÇÃO DA REDE DE ASSISTÊNCIA SOCIAL', 325000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO ACRE', 'MS/FNS', 'Ultrassom Diagnóstico / 24 Mesas de Escritório / 24 Ar Condicionados / 48 Cadeiras / 12 Computadores Portáteis (Notebook) / 4 Impressoras de Código de Barras / 4 Leitores de Código de Barras', 317000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO ACRE', 'MS/FNS', 'EQUIPAMENTOS PARA ÁREA DA SAÚDE', 999414.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO ACRE', 'MS/FNS', 'INCREMENTO PAP', 1000000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO ACRE', 'CIDADES', 'PAVIMENTAÇÃO DE VIAS URBANAS', 1050000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO ACRE', 'CIDADES', 'MANUTENÇÃO, ADEQUAÇÃO, RECUPERAÇÃO DE VIAS URBANAS', 450000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO ACRE', 'CULTURA', 'EVENTO', 200000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO ACRE', 'MIDR', 'AQUISIÇÃO DE MÁQUINAS E EQUIPAMENTOS', 1350000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO ACRE', 'ESPORTE', 'INFRAESTRUTURA ESPORTIVA - Construção, Reforma ou Ampliação de Espaços de Esporte e Lazer', 958970.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO ACRE', 'MIDR', 'ÔNIBUS EXECUTIVO 40 LUGARES', 907268.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO ACRE', 'MIDR', 'SEIS MICROTATORES (MULTICULTIVADOR) AGRICOLA 7CV', 39558.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO ACRE', 'MIDR', 'MOTONIVELADORA 125CV', 574100.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO ACRE', 'MIDR', 'RETROESCAVADEIRA 80CV', 335000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO ACRE', 'MS/FNS', 'INCREMENTO PAP', 1860000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO ACRE', 'MS/FNS', 'EQUIPAMENTOS PARA ÁREA DA SAÚDE', 328570.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO ACRE', 'MIDR', 'VEÍCULO HATCH 1.0', 101000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO WALTER', 'MIDR', 'DUAS MOTOCICLETAS BROS 160', 45980.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO WALTER', 'MS/FNS', 'INCREMENTO PAP', 391087.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO WALTER', 'ESPORTE', 'INFRAESTRUTURA ESPORTIVA: CONSTRUÇÃO DE ARQUIBANCADA E CABINE DE LOCUÇÃO', 400000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('PORTO WALTER', 'MIDR', 'DUAS CAMINHONETES PICAPE 4X4', 451690.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RIO BRANCO', 'MS/FNS', 'CUSTEIO MAC/SAÚDE', 1690000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RIO BRANCO', 'DEFESA', 'RESTAURANTE POPULAR', 2885772.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RIO BRANCO', 'DEFESA', 'CONSTRUÇÃO DA SEDE DO CONSELHO TUTELAR ', 1923850.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RIO BRANCO', 'DEFESA', '4 MOTOCICLETAS + 3 VEÍCULOS HATCH', 339854.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RIO BRANCO', 'DEFESA', '1 CAMINHÃO BASCULANTE', 583700.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RIO BRANCO', 'DEFESA', '5 ONIBUS PARA 30 PASSAGEIROS + 1 VAN PARA 15 PASSAGEIROS', 3618215.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RIO BRANCO', 'DEFESA', 'CONSTRUÇÃO DO PARQUE CIDADE DA CRIANÇA', 10393875.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RIO BRANCO', 'ESPORTE', 'REVITALIZAÇÃO DE ESPAÇOS ESPORTIVOS E DE LAZER', 1648096.66);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RIO BRANCO', 'TURISMO', 'APOIO A REALIZAÇÃO DE EVENTO', 496323.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RIO BRANCO', 'MIDR', 'VAN 16 PASSAGEIROS', 300777.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RIO BRANCO', 'MIDR', 'TRÊS CAMINHONETES PICAPE 4X4 CABINE DUPLA', 677535.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'DEFESA', 'AQUISIÇÃO DE EQUIPAMENTO AGRÍCOLA - CONJUNTO PARA BENEFECIAMENTO DE CAFÉ', 245000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'DEFESA', 'SISTEMA DE ABASTECIMENTO DE ÁGUA', 1001200.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'MS/FNS', 'Veículo e Motocicleta Para Transporte de Equipe / Ultrassom Diagnóstico / Ar Condicionado / Mesa de Escritório / Computador / Consultório Odontológico Portátil', 316873.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'DEFESA', '1 ÔNIBUS 30 PASSAGEIROS', 672700.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'MS/FNS', 'EQUIPAMENTOS PARA ÁREA DA SAÚDE', 992133.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'CIDADES', 'PAVIMENTAÇÃO DE VIAS URBANAS', 2000000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'CIDADES', 'MANUTENÇÃO, ADEQUAÇÃO, RECUPERAÇÃO DE VIAS URBANAS', 1000000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'MIDR', 'VEÍCULO HATCH 1.0', 101000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'MIDR', 'PÁ CARREGADEIRA', 287900.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'MIDR', 'CINCO TRATORES AGRICOLA 110 CV', 964995.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'MIDR', 'CAMINHONETE PICAPE 4X4 CABINE DUPLA', 225845.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'MIDR', 'DUAS ESCAVADEIRAS HIDRÁULICAS 90CV', 948400.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'MIDR', 'TRICICLO DE CARGA 149CC', 33000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'MIDR', 'SEIS QUADRICICLOS 300CC', 270000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'MIDR', 'CARRETA AGRICOLA BASCULANTE 4T', 18800.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'CIDADES', 'PAVIMENTAÇÃO DE VIAS URBANAS', 813602.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'MS/FNS', 'INCREMENTO PAP', 646140.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'MS/FNS', 'EQUIPAMENTOS PARA ÁREA DA SAÚDE', 428570.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'CULTURA', 'EVENTO GOSPEL', 300000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'ESPORTE', 'INFRAESTRUTURA ESPORTIVA: CONSTRUÇÃO DE ARQUIBANCADA NAS COMUNIDADES DA FOZ DO PARANÁ, NOVA CINTRA, SÃO GERÔNIMO E PROFETA', 1400000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'CULTURA', 'EVENTO FESTA DA BANANA', 900000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('RODRIGUES ALVES', 'TRANSPORTES/DNIT', 'CONSTRUÇÃO DA PONTE DE ACESSO A RODRIGUES ALVES - BR-364', 1000000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SANTA ROSA DO PURUS', 'MS/FNS', 'Veículo e Motocicleta Para transporte de Equipe / Bomba à Vácuo Odontológica / Câmara Escura Odontológica / Autoclave Horizontal de Mesa / Impressora Laser (Comum) / Ar Condicionado / Computador Portátil (Notebook) / Mocho / Mesa de Reunião / 2 Ar Condicionados / 3 Armários / Ultrassom Diagnóstico / Cadeira Odontológica Completa / 2 Compressores Odontológicos / Autoclave Horizontal de Mesa / Câmara Escura Odontológica / Aparelho de Raios X - Odontológico / Bomba à Vácuo Odontológica / Mocho / Consultório Odontológico Portátil', 317000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SANTA ROSA DO PURUS', 'MS/FNS', 'INCREMENTO PAP', 1000000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SANTA ROSA DO PURUS', 'MIDR', 'PÁ CARREGADEIRA 100CV', 287900.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SANTA ROSA DO PURUS', 'MIDR', 'CAMINHONETE PICAPE 4X4 CABINE DUPLA', 225845.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SANTA ROSA DO PURUS', 'MIDR', 'MICROTRATOR AGRÍCOLAS 14CV', 22309.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SANTA ROSA DO PURUS', 'MS/FNS', 'INCREMENTO PAP', 1019010.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SANTA ROSA DO PURUS', 'MIDR', 'CAMINHÃO BASCULANTE 12M³ 6X4 270CV', 594305.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SANTA ROSA DO PURUS', 'MIDR', 'CONTINUIDADE DAS OBRAS DO AERÓDROMO', 5000000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SANTA ROSA DO PURUS', 'MIDR', 'MINICARREGADEIRA 58CV', 211500.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENA MADUREIRA', 'MS/FNS', 'Veículo Pick-up Cabine Dupla 4x4 (Diesel) / 2 Balde/Lixeira / 2 Tablet / Duas Mesas para Computador / Mesa para Impressora / 4 Cadeiras / Mesa de Escritório / 2 Computadores Portáteis (Notebook) / 2 Arquivos / Ar Condicionado / Tela de Projeção / Impressora Laser Multifuncional / Duas Mesas de Escritório / Projetor Multimídia (Datashow) / 2 Armários', 317000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENA MADUREIRA', 'MS/FNS', 'CUSTEIO PAP/SAÚDE', 300000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENADOR GUIOMARD', 'DEFESA', 'PARQUE DA VAQUEJADA', 1345500.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENADOR GUIOMARD', 'MAPA', 'PÁ CARREGADEIRA SOBRE RODAS', 764800.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENADOR GUIOMARD', 'MS/FNS', 'Ultrassom Diagnóstico / Veículo e Motocicleta Para Transporte de Equipe / Consultório Odontológico / 6 Ar Condicionados / Mesa de Mayo', 316932.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENADOR GUIOMARD', 'CIDADES', 'ADEQUAÇÃO DE VIAS URBANAS', 330123.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENADOR GUIOMARD', 'CIDADES', 'PAVIMENTAÇÃO DE VIAS URBANAS', 7659482.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENADOR GUIOMARD', 'MS/FNS', 'CUSTEIO PAP/SAÚDE', 300000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENADOR GUIOMARD', 'DEFESA', '1 ÔNIBUS 30 PASSAGEIROS', 672700.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENADOR GUIOMARD', 'ESPORTE', 'REALIZAÇÃO DE EVENTOS ESPORTIVOS', 351210.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENADOR GUIOMARD', 'MIDR', 'MOTONIVELADORA / CAMINHÃO TANQUE TRANSPORTE DE 15.000 LITROS DE ÁGUA / TRATOR DE ESTEIRA 140 HP / TRATOR DE PNEU 100 CV', 3824000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENADOR GUIOMARD', 'MS/FNS', 'EQUIPAMENTOS PARA ÁREA DA SAÚDE', 998941.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENADOR GUIOMARD', 'CIDADES', 'PAVIMENTAÇÃO DE VIAS URBANAS', 6462015.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENADOR GUIOMARD', 'CIDADES', 'MANUTENÇÃO, ADEQUAÇÃO, RECUPERAÇÃO DE VIAS URBANAS', 337985.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENADOR GUIOMARD', 'MAPA', 'AQUISIÇÃO DE MÁQUINAS E EQUIPAMENTOS - CASA DE FARINHA', 337985.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENADOR GUIOMARD', 'ESPORTE', 'CONSTRUÇÃO, REFORMA  OU AMPLIAÇÃO DE ESPAÇOS DE ESPORTE E DE LAZER', 883823.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENADOR GUIOMARD', 'MIDR', 'VEÍCULO HATCH 1.0', 101000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENADOR GUIOMARD', 'MIDR', 'CAMINHÃO PIPA 12.000 LITROS 6X2 200CV', 557679.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENADOR GUIOMARD', 'MS/FNS', 'EQUIPAMENTOS PARA ÁREA DA SAÚDE', 428580.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENADOR GUIOMARD', 'MIDR', 'QUATRO TRATORES AGRÍCOLAS 110CV', 771996.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('SENADOR GUIOMARD', 'MIDR', '17 MOTOCICLETAS  160 CC', 390830.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('TARAUACÁ', 'MS/FNS', 'Ultrassom Diagnóstico / Ultrassom para Fisioterapia / DEA - Desfibrilador Externo Automático / 2 Foco Refletores Ambulatoriais / Martelo de Reflexo / Concentrador de Oxigênio / Dermatoscópio / BIPAP / 2 Estadiômetros / 2 Adipômetros / TENS - Estimulador Transcutâneo / Negatoscópio / Criocautério / Autorefrator / Oftalmoscópio / Lâmpada de Fenda / Cilindro de Gases Medicinais / Mesa Ginecológica / Bisturi Elétrico / Duas Mesas de Mayo / Manovacuômetro / FES / Cadeira / Biombo', 316998.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('TARAUACÁ', 'MAPA', '12 BARCOS DE ALUMINIO, DE 8 METROS, COM MOTOR DE 6,5 HP', 238750.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('TARAUACÁ', 'MIDR', 'TRATOR DE PNEUS 4 X 4 - 75CV', 238750.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('TARAUACÁ', 'MS/FNS', 'CUSTEIO PAP/SAÚDE', 379585.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('TARAUACÁ', 'MS/FNS', 'INCREMENTO PAP', 500000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('TARAUACÁ', 'TURISMO', 'CONSTRUÇÃO DO CENTRO DE EVENTOS', 2000000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('TARAUACÁ', 'CIDADES', 'PAVIMENTAÇÃO DE VIAS URBANAS', 813602.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('TARAUACÁ', 'TURISMO', 'CONSTRUÇÃO, REVITALIZAÇÃO E REFORMA DE ESPAÇOS TURÍSTICOS', 860661.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('TARAUACÁ', 'MS/FNS', 'INCREMENTO PAP', 500000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('TARAUACÁ', 'MIDR', 'VEICULO HATCH 1.0', 101000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('TARAUACÁ', 'MIDR', 'ÔNIBUS EXECUTIVO 40 LUGARES', 907268.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('TARAUACÁ', 'MIDR', 'ESCAVADEIRA HIDRÁULICA', 474200.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('TARAUACÁ', 'MIDR', 'DUAS VANS DE 16 PASSAGEIROS', 601554.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('TARAUACÁ', 'MIDR', 'MOTONIVELADORA - 125CV', 574100.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('TARAUACÁ', 'MIDR', 'DOIS TRATORES AGRÍCOLAS 110CV', 385998.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('TARAUACÁ', 'MS/FNS', 'INCREMENTO PAP', 2860000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('TARAUACÁ', 'TURISMO', 'CONSTRUÇÃO DA 2ª ETAPA DO CENTRO DE EVENTOS', 2000000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('TARAUACÁ', 'MS/FNS', 'CONSTRUÇÃO DE UBS NA LOCALIDADE ACURAUA', 2100000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('TARAUACÁ', 'TURISMO', 'CONSTRUÇÃO DE RAMPA DE ACESSO E HOSPEDARIA NO GREGÓRIO', 2000000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('TARAUACÁ', 'MIDR', 'RETROESCAVADEIRA 80CV', 335000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('XAPURI', 'MS/FNS', 'CONSTRUÇÃO 1ª ETAPA HOSPITAL', 5339000.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('XAPURI', 'DEFESA', '1 ÔNIBUS 30 PASSAGEIROS', 672700.0);
INSERT INTO emenda (municipio, orgao, objeto, valor) VALUES ('XAPURI', 'MIDR', 'VEÍCULO HATCH 1.0', 101000.0);